### ISSUE TITLE
Consider naming Client more specifically

### ISSUE THREAD

**Issue by tbillington** [HouraiTeahouse/bevy_steamworks#33]
The `Client` name is frequently used by many different networking libraries, and often within games themselves leading to ambiguity.

What are your thoughts on renaming the resource to be more specific, for example `SteamworksClient`?

**Comment by SDesya74** [comment]
In Rust there is an option to create an alias or rename the imported item, just for such cases. I just name it `Steam` in my projects.

**Comment by james7132** [comment]
This crate is supposed to be a thin integration between Bevy and steamworks, this is probably best upstreamed to `steamworks-rs`, and we'll just be reexporting their symbols. With that said, the naming conflict can be resolved via local type aliases, as mentioned before.
