### ISSUE TITLE
Allow checking if steam is running manually

### ISSUE THREAD

**Issue by LawyerMorty97** [HouraiTeahouse/bevy_steamworks#35]
Is it possible to check if Steam is running manually before initializing the plugin? Right now if I don't have Steam running the app doesn't start at all.

# Screenshot
<img width="645" alt="image" src="https://github.com/HouraiTeahouse/bevy_steamworks/assets/31247640/ccb36a94-dc9b-4994-af48-949d649da6a1">

**Comment by james7132** [comment]
Could you provide a more complete stack trace? The location of your panic seems to suggest that the panic is coming from your code (i.e. your own unwrap) instead of from bevy_steamworks.

**Comment by LawyerMorty97** [comment]
Stacktrace
![image](https://github.com/HouraiTeahouse/bevy_steamworks/assets/31247640/af08ece4-d862-4dc8-a559-078d0079ac3e)

**Comment by LawyerMorty97** [comment]
The "offending" code so far:
![image](https://github.com/HouraiTeahouse/bevy_steamworks/assets/31247640/0d93f616-6a4a-45e9-8425-d40dbfb7102c)

**Comment by james7132** [comment]
Line 13 in your code uses an `unwrap` which is the source of your panic. You probably want to handle the error case instead of unwrapping.

**Comment by LawyerMorty97** [comment]
Correct! Thanks for the support! I did indeed need to handle the error case!
